"""Add rating and acceptance rate to Deliverer

Revision ID: 07f60582d826
Revises: 94825232961c
Create Date: 2026-05-23 09:26:03.576918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f60582d826'
down_revision: Union[str, Sequence[str], None] = '94825232961c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deliverers', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('Deliverers', sa.Column('acceptance_rate', sa.Float(), nullable=True))
    op.create_index(op.f('ix_Deliverers_rating'), 'Deliverers', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Deliverers_rating'), table_name='Deliverers')
    op.drop_column('Deliverers', 'acceptance_rate')
    op.drop_column('Deliverers', 'rating')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
