"""multi_store_and_staff

Revision ID: 1140ea6f8341
Revises: 70d1b03c84f9
Create Date: 2026-05-27 11:40:30.865975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1140ea6f8341'
down_revision: Union[str, Sequence[str], None] = '70d1b03c84f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('Vendors', sa.Column('staff_clerk_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_Vendors_clerk_id'), table_name='Vendors')
    op.create_index(op.f('ix_Vendors_clerk_id'), 'Vendors', ['clerk_id'], unique=False)
    op.create_index(op.f('ix_Vendors_staff_clerk_id'), 'Vendors', ['staff_clerk_id'], unique=True)
    # Removed vendor_remittances alterations
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed vendor_remittances alterations
    op.drop_index(op.f('ix_Vendors_staff_clerk_id'), table_name='Vendors')
    op.drop_index(op.f('ix_Vendors_clerk_id'), table_name='Vendors')
    op.create_index(op.f('ix_Vendors_clerk_id'), 'Vendors', ['clerk_id'], unique=True)
    op.drop_column('Vendors', 'staff_clerk_id')
    # Removed spatial_ref_sys creation
    # ### end Alembic commands ###
