"""Add JSONB data field to Notifications

Revision ID: 312b7bf2eb8c
Revises: 37733966129c
Create Date: 2026-04-27 12:36:09.506616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '312b7bf2eb8c'
down_revision: Union[str, Sequence[str], None] = '37733966129c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notifications', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('VendorRiderRegistry_rider_id_fkey'), 'VendorRiderRegistry', type_='foreignkey')
    op.create_foreign_key(None, 'VendorRiderRegistry', 'Deliverers', ['rider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'VendorRiderRegistry', type_='foreignkey')
    op.create_foreign_key(op.f('VendorRiderRegistry_rider_id_fkey'), 'VendorRiderRegistry', 'Users', ['rider_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Notifications', 'data')
    # ### end Alembic commands ###
