"""Add OrderTrackingLog model

Revision ID: 3b54c09377ba
Revises: 6fe29d0b77a2
Create Date: 2026-06-16 13:39:13.137394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b54c09377ba'
down_revision: Union[str, Sequence[str], None] = '6fe29d0b77a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Order_Tracking_Logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_tracking_order_id_created', 'Order_Tracking_Logs', ['order_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_Order_Tracking_Logs_created_at'), 'Order_Tracking_Logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_Order_Tracking_Logs_id'), 'Order_Tracking_Logs', ['id'], unique=True)
    op.create_index(op.f('ix_Order_Tracking_Logs_order_id'), 'Order_Tracking_Logs', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Order_Tracking_Logs_order_id'), table_name='Order_Tracking_Logs')
    op.drop_index(op.f('ix_Order_Tracking_Logs_id'), table_name='Order_Tracking_Logs')
    op.drop_index(op.f('ix_Order_Tracking_Logs_created_at'), table_name='Order_Tracking_Logs')
    op.drop_index('idx_order_tracking_order_id_created', table_name='Order_Tracking_Logs')
    op.drop_table('Order_Tracking_Logs')
    # ### end Alembic commands ###
