"""dual_tier_logistics

Revision ID: 3ba669eb21f3
Revises: a36f089659d0
Create Date: 2026-05-21 15:49:31.069031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ba669eb21f3'
down_revision: Union[str, Sequence[str], None] = 'a36f089659d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Deliverer_Vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deliverer_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', name='vendorriderstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deliverer_id'], ['Deliverers.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Deliverer_Vendors_deliverer_id'), 'Deliverer_Vendors', ['deliverer_id'], unique=False)
    op.create_index(op.f('ix_Deliverer_Vendors_id'), 'Deliverer_Vendors', ['id'], unique=False)
    op.create_index(op.f('ix_Deliverer_Vendors_vendor_id'), 'Deliverer_Vendors', ['vendor_id'], unique=False)
    op.create_table('Bottle_Rejection_Tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'DENIED', name='rejectionstatus'), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('photo_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['Deliverers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Bottle_Rejection_Tickets_id'), 'Bottle_Rejection_Tickets', ['id'], unique=False)
    op.create_index(op.f('ix_Bottle_Rejection_Tickets_order_id'), 'Bottle_Rejection_Tickets', ['order_id'], unique=False)
    op.create_index(op.f('ix_Bottle_Rejection_Tickets_rider_id'), 'Bottle_Rejection_Tickets', ['rider_id'], unique=False)
    op.add_column('Deliverers', sa.Column('operation_lat', sa.Float(), nullable=True))
    op.add_column('Deliverers', sa.Column('operation_lng', sa.Float(), nullable=True))
    op.add_column('Orders', sa.Column('delivery_type', sa.String(), nullable=False, server_default=sa.text("'quick_swap'")))
    op.add_column('Orders', sa.Column('bottle_source', sa.String(), nullable=False, server_default=sa.text("'platform'")))
    op.drop_column('Orders', 'deposit_waived_amount')
    op.drop_column('Orders', 'deposit_charged_at_door')
    op.drop_column('Orders', 'empties_expected')
    op.drop_column('Orders', 'empties_received')
    op.add_column('Users', sa.Column('bottle_purchased_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('Users', sa.Column('bottle_refill_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.drop_column('Users', 'empty_bottles_held')
    op.drop_column('Users', 'active_deposits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('active_deposits', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('Users', sa.Column('empty_bottles_held', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('Users', 'bottle_refill_count')
    op.drop_column('Users', 'bottle_purchased_at')
    op.add_column('Orders', sa.Column('empties_received', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('Orders', sa.Column('empties_expected', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('Orders', sa.Column('deposit_charged_at_door', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('Orders', sa.Column('deposit_waived_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('Orders', 'bottle_source')
    op.drop_column('Orders', 'delivery_type')
    op.drop_column('Deliverers', 'operation_lng')
    op.drop_column('Deliverers', 'operation_lat')
    op.drop_index(op.f('ix_Bottle_Rejection_Tickets_rider_id'), table_name='Bottle_Rejection_Tickets')
    op.drop_index(op.f('ix_Bottle_Rejection_Tickets_order_id'), table_name='Bottle_Rejection_Tickets')
    op.drop_index(op.f('ix_Bottle_Rejection_Tickets_id'), table_name='Bottle_Rejection_Tickets')
    op.drop_table('Bottle_Rejection_Tickets')
    op.drop_index(op.f('ix_Deliverer_Vendors_vendor_id'), table_name='Deliverer_Vendors')
    op.drop_index(op.f('ix_Deliverer_Vendors_id'), table_name='Deliverer_Vendors')
    op.drop_index(op.f('ix_Deliverer_Vendors_deliverer_id'), table_name='Deliverer_Vendors')
    op.drop_table('Deliverer_Vendors')
    # ### end Alembic commands ###
