"""Add cancellation_reason to Order

Revision ID: 3bda9b1138d8
Revises: 886255648669
Create Date: 2026-06-12 15:32:56.064807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bda9b1138d8'
down_revision: Union[str, Sequence[str], None] = '886255648669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('cancellation_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'cancellation_reason')
    # ### end Alembic commands ###
