"""Add welcome offer and device tracking fields

Revision ID: 409d30504073
Revises: c68829a7b7df
Create Date: 2026-04-25 01:17:22.308051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409d30504073'
down_revision: Union[str, Sequence[str], None] = 'c68829a7b7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('is_welcome_offer', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('Orders', sa.Column('deposit_waived_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('Users', sa.Column('has_used_welcome_offer', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('Users', sa.Column('device_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_Users_device_id'), 'Users', ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_device_id'), table_name='Users')
    op.drop_column('Users', 'device_id')
    op.drop_column('Users', 'has_used_welcome_offer')
    op.drop_column('Orders', 'deposit_waived_amount')
    op.drop_column('Orders', 'is_welcome_offer')
    # ### end Alembic commands ###
