"""add is_online to vendors

Revision ID: 412f43743aad
Revises: a1b2c3d4e5f6
Create Date: 2026-05-01 10:50:01.461298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412f43743aad'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='Products')
    op.create_index(op.f('ix_Products_category'), 'Products', ['category'], unique=False)
    op.add_column('Vendors', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_Vendors_is_online'), 'Vendors', ['is_online'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Vendors_is_online'), table_name='Vendors')
    op.drop_column('Vendors', 'is_online')
    op.drop_index(op.f('ix_Products_category'), table_name='Products')
    op.create_index(op.f('ix_products_category'), 'Products', ['category'], unique=False)
    # ### end Alembic commands ###
