"""add_discount_fields

Revision ID: 5f36cbc0c27a
Revises: 3b54c09377ba
Create Date: 2026-06-20 11:33:18.138292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f36cbc0c27a'
down_revision: Union[str, Sequence[str], None] = '3b54c09377ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('wallet_discount', sa.Numeric(precision=10, scale=2), nullable=False, server_default="0.00"))
    op.add_column('Orders', sa.Column('welcome_discount', sa.Numeric(precision=10, scale=2), nullable=False, server_default="0.00"))
    op.add_column('Orders', sa.Column('product_subtotal', sa.Numeric(precision=10, scale=2), nullable=False, server_default="0.00"))
    op.create_index('idx_orders_customer_status', 'Orders', ['customer_id', 'order_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orders_customer_status', table_name='Orders')
    op.drop_column('Orders', 'product_subtotal')
    op.drop_column('Orders', 'welcome_discount')
    op.drop_column('Orders', 'wallet_discount')
    # ### end Alembic commands ###
