"""fix review unique constraint to allow vendor+rider review per order

Revision ID: 6c4a64c43cb7
Revises: fdc104a047c6
Create Date: 2026-07-20 23:18:47.055447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4a64c43cb7'
down_revision: Union[str, Sequence[str], None] = 'fdc104a047c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_customer_order_review'), 'reviews', type_='unique')
    op.create_unique_constraint('uq_customer_order_target_review', 'reviews', ['customer_clerk_id', 'order_id', 'target_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customer_order_target_review', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('uq_customer_order_review'), 'reviews', ['customer_clerk_id', 'order_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
