"""Add wholesale delivery pricing and update deposit default

Revision ID: 6dfff833cf6f
Revises: 3690bd78e546
Create Date: 2026-05-17 23:54:25.997179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dfff833cf6f'
down_revision: Union[str, Sequence[str], None] = '3690bd78e546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Saved_Locations_id'), 'Saved_Locations', ['id'], unique=False)
    op.add_column('Vendors', sa.Column('wholesale_base_delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('Vendors', sa.Column('wholesale_per_km_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Vendors', 'wholesale_per_km_fee')
    op.drop_column('Vendors', 'wholesale_base_delivery_fee')
    op.drop_index(op.f('ix_Saved_Locations_id'), table_name='Saved_Locations')
    # ### end Alembic commands ###
