"""Add h3_index_res8 to vendor

Revision ID: 6fe29d0b77a2
Revises: ef84f79af8e4
Create Date: 2026-06-16 11:06:04.592317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe29d0b77a2'
down_revision: Union[str, Sequence[str], None] = 'ef84f79af8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vendors', sa.Column('h3_index_res8', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_Vendors_h3_index_res8'), 'Vendors', ['h3_index_res8'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Vendors_h3_index_res8'), table_name='Vendors')
    op.drop_column('Vendors', 'h3_index_res8')
    # ### end Alembic commands ###
