"""Add KYC fields to Deliverer

Revision ID: 70d1b03c84f9
Revises: f89b5f238dc6
Create Date: 2026-05-25 06:13:35.793713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70d1b03c84f9'
down_revision: Union[str, Sequence[str], None] = 'f89b5f238dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    kyc_enum = postgresql.ENUM('unsubmitted', 'pending', 'approved', 'rejected', name='deliverer_kyc_status')
    kyc_enum.create(op.get_bind())
    op.add_column('Deliverers', sa.Column('id_card_front', sa.Text(), nullable=True))
    op.add_column('Deliverers', sa.Column('id_card_back', sa.Text(), nullable=True))
    op.add_column('Deliverers', sa.Column('kyc_status', sa.Enum('unsubmitted', 'pending', 'approved', 'rejected', name='deliverer_kyc_status'), server_default='unsubmitted', nullable=False))
    op.create_index(op.f('ix_Deliverers_kyc_status'), 'Deliverers', ['kyc_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Deliverers_kyc_status'), table_name='Deliverers')
    op.drop_column('Deliverers', 'kyc_status')
    op.drop_column('Deliverers', 'id_card_back')
    op.drop_column('Deliverers', 'id_card_front')
    postgresql.ENUM(name='deliverer_kyc_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
