"""Add idempotency_key to payouts

Revision ID: 7955e9ded0f3
Revises: staff_push_token_add
Create Date: 2026-05-30 07:11:58.433419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7955e9ded0f3'
down_revision: Union[str, Sequence[str], None] = 'staff_push_token_add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.add_column('payouts', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payouts_idempotency_key'), 'payouts', ['idempotency_key'], unique=True)
    op.alter_column('vendor_remittances', 'status',
               existing_type=postgresql.ENUM('OPEN', 'SETTLED', 'DISCREPANCY', name='gatepassstatus'),
               type_=sa.Enum('OPEN', 'SETTLED', 'DISCREPANCY', name='vendorremittancestatus'),
               existing_nullable=True)
    op.drop_index(op.f('idx_gatepass_deliverer_created'), table_name='vendor_remittances')
    op.drop_index(op.f('idx_gatepass_vendor_created'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_GatePasses_deliverer_id'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_GatePasses_id'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_GatePasses_vendor_id'), table_name='vendor_remittances')
    op.create_index('idx_vendor_remittance_deliverer_created', 'vendor_remittances', ['deliverer_id', 'created_at'], unique=False)
    op.create_index('idx_vendor_remittance_vendor_created', 'vendor_remittances', ['vendor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_vendor_remittances_deliverer_id'), 'vendor_remittances', ['deliverer_id'], unique=False)
    op.create_index(op.f('ix_vendor_remittances_id'), 'vendor_remittances', ['id'], unique=True)
    op.create_index(op.f('ix_vendor_remittances_vendor_id'), 'vendor_remittances', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_remittances_vendor_id'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_vendor_remittances_id'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_vendor_remittances_deliverer_id'), table_name='vendor_remittances')
    op.drop_index('idx_vendor_remittance_vendor_created', table_name='vendor_remittances')
    op.drop_index('idx_vendor_remittance_deliverer_created', table_name='vendor_remittances')
    op.create_index(op.f('ix_GatePasses_vendor_id'), 'vendor_remittances', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_GatePasses_id'), 'vendor_remittances', ['id'], unique=True)
    op.create_index(op.f('ix_GatePasses_deliverer_id'), 'vendor_remittances', ['deliverer_id'], unique=False)
    op.create_index(op.f('idx_gatepass_vendor_created'), 'vendor_remittances', ['vendor_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_gatepass_deliverer_created'), 'vendor_remittances', ['deliverer_id', 'created_at'], unique=False)
    op.alter_column('vendor_remittances', 'status',
               existing_type=sa.Enum('OPEN', 'SETTLED', 'DISCREPANCY', name='vendorremittancestatus'),
               type_=postgresql.ENUM('OPEN', 'SETTLED', 'DISCREPANCY', name='gatepassstatus'),
               existing_nullable=True)
    op.drop_index(op.f('ix_payouts_idempotency_key'), table_name='payouts')
    op.drop_column('payouts', 'idempotency_key')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
