"""Add pending bottle columns to VendorRiderRegistry

Revision ID: 795f0931ffa0
Revises: 5b06c684a724
Create Date: 2026-06-15 14:20:06.686866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795f0931ffa0'
down_revision: Union[str, Sequence[str], None] = '5b06c684a724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_products_search_vector', 'Products', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('VendorRiderRegistry', sa.Column('pending_10L_empties', sa.Integer(), nullable=False))
    op.add_column('VendorRiderRegistry', sa.Column('pending_20L_empties', sa.Integer(), nullable=False))
    op.create_index('idx_vendors_search_vector', 'Vendors', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vendors_search_vector', table_name='Vendors', postgresql_using='gin')
    op.drop_column('VendorRiderRegistry', 'pending_20L_empties')
    op.drop_column('VendorRiderRegistry', 'pending_10L_empties')
    op.drop_index('idx_products_search_vector', table_name='Products', postgresql_using='gin')
    # ### end Alembic commands ###
