"""add preferences and payment_methods to user

Revision ID: 7a4f8fa83f1f
Revises: 7645438dc804
Create Date: 2026-05-10 13:40:11.236363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a4f8fa83f1f'
down_revision: Union[str, Sequence[str], None] = '7645438dc804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{"order_updates": true, "promotions": false, "delivery_reminders": true, "analytics": true}', nullable=False))
    op.add_column('Users', sa.Column('payment_methods', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'payment_methods')
    op.drop_column('Users', 'preferences')
    # ### end Alembic commands ###
