"""Add zone tracking to rider

Revision ID: 7d0ed2d1a565
Revises: 3ba669eb21f3
Create Date: 2026-05-22 18:15:04.030683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0ed2d1a565'
down_revision: Union[str, Sequence[str], None] = '3ba669eb21f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deliverers', sa.Column('zone_changes_this_month', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('Deliverers', sa.Column('last_zone_change', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Deliverers', 'last_zone_change')
    op.drop_column('Deliverers', 'zone_changes_this_month')
    # ### end Alembic commands ###
