"""Add spatial GIST index bounds

Revision ID: 7f6a28d33b0e
Revises: 
Create Date: 2026-04-21 03:32:31.371698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f6a28d33b0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('related_order_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('delivered_via', sa.String(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Notifications_delivered_via'), 'Notifications', ['delivered_via'], unique=False)
    op.create_index(op.f('ix_Notifications_id'), 'Notifications', ['id'], unique=True)
    op.create_index(op.f('ix_Notifications_is_read'), 'Notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_Notifications_message_type'), 'Notifications', ['message_type'], unique=False)
    op.create_index(op.f('ix_Notifications_related_order_id'), 'Notifications', ['related_order_id'], unique=False)
    op.create_index(op.f('ix_Notifications_title'), 'Notifications', ['title'], unique=False)
    op.create_index(op.f('ix_Notifications_user_id'), 'Notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_Notifications_user_type'), 'Notifications', ['user_type'], unique=False)
    op.create_table('GatePasses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('deliverer_id', sa.UUID(), nullable=True),
    sa.Column('full_bottles_out', sa.Integer(), nullable=False),
    sa.Column('full_bottles_returned', sa.Integer(), nullable=False),
    sa.Column('empty_bottles_collected', sa.Integer(), nullable=False),
    sa.Column('cash_expected', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_collected', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SETTLED', 'DISCREPANCY', name='gatepassstatus'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deliverer_id'], ['Deliverers.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GatePasses_deliverer_id'), 'GatePasses', ['deliverer_id'], unique=False)
    op.create_index(op.f('ix_GatePasses_id'), 'GatePasses', ['id'], unique=True)
    op.create_index(op.f('ix_GatePasses_vendor_id'), 'GatePasses', ['vendor_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('checkout_request_id', sa.String(), nullable=False),
    sa.Column('mpesa_receipt', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_checkout_request_id'), 'payments', ['checkout_request_id'], unique=True)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_mpesa_receipt'), 'payments', ['mpesa_receipt'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_unique_constraint('uq_cart_product', 'Cart_Items', ['cart_id', 'product_id'])
    op.create_index('idx_deliverer_location_gist', 'Deliverers', ['location'], unique=False, postgresql_using='gist')
    op.create_unique_constraint('uq_user_product_favorite', 'Favorites', ['user_id', 'product_id'])
    op.add_column('Orders', sa.Column('empties_expected', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('Orders', sa.Column('empties_received', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('Orders', sa.Column('deposit_charged_at_door', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('Orders', sa.Column('proof_url', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('active_deposits', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('Users', sa.Column('empty_bottles_held', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('Users', sa.Column('last_order_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('Users', sa.Column('debt_balance', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    op.create_index('idx_user_location_gist', 'Users', ['location'], unique=False, postgresql_using='gist')
    op.add_column('Vendors', sa.Column('deposit_fee', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    op.add_column('Vendors', sa.Column('empty_bottle_inventory', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('Vendors', sa.Column('full_bottle_inventory', sa.Integer(), nullable=False, server_default='0'))
    op.create_index('idx_vendor_location_gist', 'Vendors', ['location'], unique=False, postgresql_using='gist')
    op.add_column('payouts', sa.Column('conversation_id', sa.String(length=255), nullable=True))
    op.add_column('payouts', sa.Column('mpesa_receipt', sa.String(length=255), nullable=True))
    op.add_column('payouts', sa.Column('failure_reason', sa.String(length=500), nullable=True))
    op.alter_column('payouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payouts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_payouts_conversation_id'), 'payouts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_payouts_mpesa_receipt'), 'payouts', ['mpesa_receipt'], unique=False)
    op.create_unique_constraint('uq_customer_order_review', 'reviews', ['customer_clerk_id', 'order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customer_order_review', 'reviews', type_='unique')
    op.drop_index(op.f('ix_payouts_mpesa_receipt'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_conversation_id'), table_name='payouts')
    op.alter_column('payouts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payouts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('payouts', 'failure_reason')
    op.drop_column('payouts', 'mpesa_receipt')
    op.drop_column('payouts', 'conversation_id')
    op.drop_index('idx_vendor_location_gist', table_name='Vendors', postgresql_using='gist')
    op.drop_column('Vendors', 'full_bottle_inventory')
    op.drop_column('Vendors', 'empty_bottle_inventory')
    op.drop_column('Vendors', 'deposit_fee')
    op.drop_index('idx_user_location_gist', table_name='Users', postgresql_using='gist')
    op.drop_column('Users', 'debt_balance')
    op.drop_column('Users', 'last_order_date')
    op.drop_column('Users', 'empty_bottles_held')
    op.drop_column('Users', 'active_deposits')
    op.drop_column('Orders', 'proof_url')
    op.drop_column('Orders', 'deposit_charged_at_door')
    op.drop_column('Orders', 'empties_received')
    op.drop_column('Orders', 'empties_expected')
    op.drop_constraint('uq_user_product_favorite', 'Favorites', type_='unique')
    op.drop_index('idx_deliverer_location_gist', table_name='Deliverers', postgresql_using='gist')
    op.drop_constraint('uq_cart_product', 'Cart_Items', type_='unique')
    # spatial_ref_sys ignored
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_mpesa_receipt'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_checkout_request_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_GatePasses_vendor_id'), table_name='GatePasses')
    op.drop_index(op.f('ix_GatePasses_id'), table_name='GatePasses')
    op.drop_index(op.f('ix_GatePasses_deliverer_id'), table_name='GatePasses')
    op.drop_table('GatePasses')
    op.drop_index(op.f('ix_Notifications_user_type'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_user_id'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_title'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_related_order_id'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_message_type'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_is_read'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_id'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_delivered_via'), table_name='Notifications')
    op.drop_table('Notifications')
    # ### end Alembic commands ###
