"""add_VendorRiderRegistry_table

Revision ID: 8631dd68b75f
Revises: bf4eb84e3815
Create Date: 2026-04-23 22:40:13.601953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8631dd68b75f'
down_revision: Union[str, Sequence[str], None] = 'bf4eb84e3815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('h3_index_res8', sa.String(length=16), nullable=True))
    op.add_column('Orders', sa.Column('distance_km', sa.Double(), nullable=True))
    op.create_index(op.f('ix_Orders_h3_index_res8'), 'Orders', ['h3_index_res8'], unique=False)
    op.add_column('Users', sa.Column('h3_index_res8', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_Users_h3_index_res8'), 'Users', ['h3_index_res8'], unique=False)
    op.add_column('VendorRiderRegistry', sa.Column('rider_id', sa.UUID(), nullable=False))
    op.add_column('VendorRiderRegistry', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('VendorRiderRegistry', sa.Column('h3_index', sa.String(length=20), nullable=True))
    op.add_column('VendorRiderRegistry', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('VendorRiderRegistry', sa.Column('requested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('VendorRiderRegistry', sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('VendorRiderRegistry', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_VendorRiderRegistry_deliverer_id'), table_name='VendorRiderRegistry')
    op.drop_index(op.f('ix_VendorRiderRegistry_status'), table_name='VendorRiderRegistry')
    op.create_index(op.f('ix_VendorRiderRegistry_h3_index'), 'VendorRiderRegistry', ['h3_index'], unique=False)
    op.create_index(op.f('ix_VendorRiderRegistry_rider_id'), 'VendorRiderRegistry', ['rider_id'], unique=False)
    op.drop_constraint(op.f('VendorRiderRegistry_deliverer_id_fkey'), 'VendorRiderRegistry', type_='foreignkey')
    op.create_foreign_key(None, 'VendorRiderRegistry', 'Users', ['rider_id'], ['id'], ondelete='CASCADE')
    op.drop_column('VendorRiderRegistry', 'deliverer_id')
    op.drop_column('VendorRiderRegistry', 'created_at')
    op.drop_column('VendorRiderRegistry', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VendorRiderRegistry', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('VendorRiderRegistry', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('VendorRiderRegistry', sa.Column('deliverer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'VendorRiderRegistry', type_='foreignkey')
    op.create_foreign_key(op.f('VendorRiderRegistry_deliverer_id_fkey'), 'VendorRiderRegistry', 'Deliverers', ['deliverer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_VendorRiderRegistry_rider_id'), table_name='VendorRiderRegistry')
    op.drop_index(op.f('ix_VendorRiderRegistry_h3_index'), table_name='VendorRiderRegistry')
    op.create_index(op.f('ix_VendorRiderRegistry_status'), 'VendorRiderRegistry', ['status'], unique=False)
    op.create_index(op.f('ix_VendorRiderRegistry_deliverer_id'), 'VendorRiderRegistry', ['deliverer_id'], unique=False)
    op.alter_column('VendorRiderRegistry', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('VendorRiderRegistry', 'approved_at')
    op.drop_column('VendorRiderRegistry', 'requested_at')
    op.drop_column('VendorRiderRegistry', 'distance_km')
    op.drop_column('VendorRiderRegistry', 'h3_index')
    op.drop_column('VendorRiderRegistry', 'priority')
    op.drop_column('VendorRiderRegistry', 'rider_id')
    op.drop_index(op.f('ix_Users_h3_index_res8'), table_name='Users')
    op.drop_column('Users', 'h3_index_res8')
    op.drop_index(op.f('ix_Orders_h3_index_res8'), table_name='Orders')
    op.drop_column('Orders', 'distance_km')
    op.drop_column('Orders', 'h3_index_res8')
    # spatial_ref_sys ignored
    # ### end Alembic commands ###
