"""Add actual_floor_level to Order model

Revision ID: 886255648669
Revises: 95436416fa26
Create Date: 2026-06-12 14:28:40.820604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886255648669'
down_revision: Union[str, Sequence[str], None] = '95436416fa26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('actual_floor_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'actual_floor_level')
    # ### end Alembic commands ###
