"""add_preferences_and_payment_methods_to_deliverer

Revision ID: 94825232961c
Revises: 7d0ed2d1a565
Create Date: 2026-05-22 22:27:44.693200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94825232961c'
down_revision: Union[str, Sequence[str], None] = '7d0ed2d1a565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deliverers', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('Deliverers', sa.Column('payment_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Deliverers', 'payment_methods')
    op.drop_column('Deliverers', 'preferences')
    # ### end Alembic commands ###
