"""Add is_locked to Cart

Revision ID: a037bb423875
Revises: 7955e9ded0f3
Create Date: 2026-06-11 22:53:29.715585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a037bb423875'
down_revision: Union[str, Sequence[str], None] = '7955e9ded0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Carts', sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('payments', sa.Column('reversal_conversation_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_reversal_conversation_id'), 'payments', ['reversal_conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_reversal_conversation_id'), table_name='payments')
    op.drop_column('payments', 'reversal_conversation_id')
    op.drop_column('Carts', 'is_locked')
    # ### end Alembic commands ###
