"""add wallet_balance to users

Revision ID: a36f089659d0
Revises: 6dfff833cf6f
Create Date: 2026-05-20 10:39:53.296040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36f089659d0'
down_revision: Union[str, Sequence[str], None] = '6dfff833cf6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deliverers', sa.Column('is_platinum', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_Deliverers_is_platinum'), 'Deliverers', ['is_platinum'], unique=False)
    op.create_index('idx_gatepass_deliverer_created', 'GatePasses', ['deliverer_id', 'created_at'], unique=False)
    op.create_index('idx_gatepass_vendor_created', 'GatePasses', ['vendor_id', 'created_at'], unique=False)
    op.create_index('idx_notif_user_type_read', 'Notifications', ['user_id', 'user_type', 'is_read'], unique=False)
    op.add_column('Orders', sa.Column('vendor_commission', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('Orders', sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('Orders', sa.Column('rider_commission', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('Orders', sa.Column('platform_total', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('Orders', sa.Column('vendor_net', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('Orders', sa.Column('rider_net', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('Orders', sa.Column('surge_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('Orders', sa.Column('delivery_markup', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('Orders', sa.Column('commission_lost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('Orders', sa.Column('staircase_surcharge', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
    op.add_column('Orders', sa.Column('payload_surcharge', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
    op.create_index('idx_orders_customer_created', 'Orders', ['customer_id', 'created_at'], unique=False)
    op.create_index('idx_orders_deliverer_created', 'Orders', ['deliverer_id', 'created_at'], unique=False)
    op.create_index('idx_orders_vendor_created', 'Orders', ['vendor_id', 'created_at'], unique=False)
    op.drop_index(op.f('idx_products_search_vector'), table_name='Products', postgresql_using='gin')
    op.create_index('idx_product_category_available', 'Products', ['category', 'is_available', 'created_at'], unique=False)
    op.create_index('idx_product_discount_created', 'Products', ['discount', 'created_at'], unique=False)
    op.create_index('idx_saved_loc_user_default_last_used', 'Saved_Locations', ['user_id', 'is_default', 'last_used_at'], unique=False)
    op.add_column('Users', sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
    op.add_column('Users', sa.Column('floor_level', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('Users', sa.Column('has_elevator', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_index(op.f('idx_vendors_search_vector'), table_name='Vendors', postgresql_using='gin')
    op.create_index('idx_vendor_type_rating', 'Vendors', ['vendor_type', 'rating'], unique=False)
    op.create_index('idx_payout_provider_created', 'payouts', ['provider_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payout_provider_created', table_name='payouts')
    op.drop_index('idx_vendor_type_rating', table_name='Vendors')
    op.create_index(op.f('idx_vendors_search_vector'), 'Vendors', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('Users', 'has_elevator')
    op.drop_column('Users', 'floor_level')
    op.drop_column('Users', 'wallet_balance')
    op.drop_index('idx_saved_loc_user_default_last_used', table_name='Saved_Locations')
    op.drop_index('idx_product_discount_created', table_name='Products')
    op.drop_index('idx_product_category_available', table_name='Products')
    op.create_index(op.f('idx_products_search_vector'), 'Products', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_index('idx_orders_vendor_created', table_name='Orders')
    op.drop_index('idx_orders_deliverer_created', table_name='Orders')
    op.drop_index('idx_orders_customer_created', table_name='Orders')
    op.drop_column('Orders', 'payload_surcharge')
    op.drop_column('Orders', 'staircase_surcharge')
    op.drop_column('Orders', 'commission_lost')
    op.drop_column('Orders', 'delivery_markup')
    op.drop_column('Orders', 'surge_fee')
    op.drop_column('Orders', 'rider_net')
    op.drop_column('Orders', 'vendor_net')
    op.drop_column('Orders', 'platform_total')
    op.drop_column('Orders', 'rider_commission')
    op.drop_column('Orders', 'service_fee')
    op.drop_column('Orders', 'vendor_commission')
    op.drop_index('idx_notif_user_type_read', table_name='Notifications')
    op.drop_index('idx_gatepass_vendor_created', table_name='GatePasses')
    op.drop_index('idx_gatepass_deliverer_created', table_name='GatePasses')
    op.drop_index(op.f('ix_Deliverers_is_platinum'), table_name='Deliverers')
    op.drop_column('Deliverers', 'is_platinum')
    # ### end Alembic commands ###
