"""Add VendorRiderRegistry table

Revision ID: bf4eb84e3815
Revises: 7f6a28d33b0e
Create Date: 2026-04-21 15:36:27.841421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4eb84e3815'
down_revision: Union[str, Sequence[str], None] = '7f6a28d33b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VendorRiderRegistry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('deliverer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deliverer_id'], ['Deliverers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_VendorRiderRegistry_deliverer_id'), 'VendorRiderRegistry', ['deliverer_id'], unique=False)
    op.create_index(op.f('ix_VendorRiderRegistry_id'), 'VendorRiderRegistry', ['id'], unique=False)
    op.create_index(op.f('ix_VendorRiderRegistry_status'), 'VendorRiderRegistry', ['status'], unique=False)
    op.create_index(op.f('ix_VendorRiderRegistry_vendor_id'), 'VendorRiderRegistry', ['vendor_id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostGIS table ignored
    op.drop_index(op.f('ix_VendorRiderRegistry_vendor_id'), table_name='VendorRiderRegistry')
    op.drop_index(op.f('ix_VendorRiderRegistry_status'), table_name='VendorRiderRegistry')
    op.drop_index(op.f('ix_VendorRiderRegistry_id'), table_name='VendorRiderRegistry')
    op.drop_index(op.f('ix_VendorRiderRegistry_deliverer_id'), table_name='VendorRiderRegistry')
    op.drop_table('VendorRiderRegistry')
    # ### end Alembic commands ###
