"""Add h3_index_res8 to Deliverer

Revision ID: c68829a7b7df
Revises: 8631dd68b75f
Create Date: 2026-04-24 23:30:43.710586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68829a7b7df'
down_revision: Union[str, Sequence[str], None] = '8631dd68b75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deliverers', sa.Column('h3_index_res8', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_Deliverers_h3_index_res8'), 'Deliverers', ['h3_index_res8'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Deliverers_h3_index_res8'), table_name='Deliverers')
    op.drop_column('Deliverers', 'h3_index_res8')
    # ### end Alembic commands ###
