"""Add V6 wholesale logistics models

Revision ID: e875588ba923
Revises: 409d30504073
Create Date: 2026-04-26 21:30:21.355350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e875588ba923'
down_revision: Union[str, Sequence[str], None] = '409d30504073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE rider_employment_type AS ENUM ('gig_economy', 'in_house')")
    op.execute("CREATE TYPE rider_vehicle_type AS ENUM ('motorbike', 'tuktuk', 'truck')")
    op.execute("CREATE TYPE vendor_business_type AS ENUM ('retail_refill', 'wholesale_b2b')")

    op.add_column('Deliverers', sa.Column('employment_model', sa.Enum('gig_economy', 'in_house', name='rider_employment_type'), nullable=False, server_default='gig_economy'))
    op.add_column('Deliverers', sa.Column('employer_vendor_id', sa.UUID(), nullable=True))
    
    op.execute("ALTER TABLE \"Deliverers\" ALTER COLUMN vehicle_type TYPE rider_vehicle_type USING CASE WHEN vehicle_type IN ('motorbike', 'tuktuk', 'truck') THEN vehicle_type::rider_vehicle_type ELSE 'motorbike'::rider_vehicle_type END")
    op.execute("ALTER TABLE \"Deliverers\" ALTER COLUMN vehicle_type DROP DEFAULT")

    op.create_index(op.f('ix_Deliverers_employer_vendor_id'), 'Deliverers', ['employer_vendor_id'], unique=False)
    op.create_index(op.f('ix_Deliverers_employment_model'), 'Deliverers', ['employment_model'], unique=False)
    op.create_foreign_key(None, 'Deliverers', 'Vendors', ['employer_vendor_id'], ['id'], ondelete='SET NULL')
    op.add_column('Products', sa.Column('weight_kg', sa.Float(), nullable=False, server_default='20.0'))
    op.add_column('Products', sa.Column('minimum_order_qty', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_Products_minimum_order_qty'), 'Products', ['minimum_order_qty'], unique=False)
    op.create_index(op.f('ix_Products_weight_kg'), 'Products', ['weight_kg'], unique=False)
    op.execute("ALTER TABLE \"Vendors\" ALTER COLUMN vendor_type TYPE vendor_business_type USING CASE WHEN vendor_type IN ('retail_refill', 'wholesale_b2b') THEN vendor_type::vendor_business_type ELSE 'retail_refill'::vendor_business_type END")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Vendors', 'vendor_type',
               existing_type=sa.Enum('retail_refill', 'wholesale_b2b', name='vendor_business_type'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_Products_weight_kg'), table_name='Products')
    op.drop_index(op.f('ix_Products_minimum_order_qty'), table_name='Products')
    op.drop_column('Products', 'minimum_order_qty')
    op.drop_column('Products', 'weight_kg')
    op.drop_constraint(None, 'Deliverers', type_='foreignkey')
    op.drop_index(op.f('ix_Deliverers_employment_model'), table_name='Deliverers')
    op.drop_index(op.f('ix_Deliverers_employer_vendor_id'), table_name='Deliverers')
    op.execute("ALTER TABLE \"Deliverers\" ALTER COLUMN vehicle_type TYPE VARCHAR USING vehicle_type::VARCHAR")
    op.drop_column('Deliverers', 'employer_vendor_id')
    op.drop_column('Deliverers', 'employment_model')
    op.execute("DROP TYPE rider_employment_type")
    op.execute("DROP TYPE rider_vehicle_type")
    op.execute("DROP TYPE vendor_business_type")
    # ### end Alembic commands ###
