"""Add wallet_balance to Deliverer

Revision ID: eb8d94b0bbec
Revises: 795f0931ffa0
Create Date: 2026-06-15 14:36:32.866091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8d94b0bbec'
down_revision: Union[str, Sequence[str], None] = '795f0931ffa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deliverers', sa.Column('wallet_balance', sa.Float(), nullable=False, server_default='0.0'))
    op.create_index(op.f('ix_Deliverers_wallet_balance'), 'Deliverers', ['wallet_balance'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Deliverers_wallet_balance'), table_name='Deliverers')
    op.drop_column('Deliverers', 'wallet_balance')
    # ### end Alembic commands ###
