"""Add Wallet Transactions

Revision ID: ef84f79af8e4
Revises: eb8d94b0bbec
Create Date: 2026-06-15 15:52:21.333278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef84f79af8e4'
down_revision: Union[str, Sequence[str], None] = 'eb8d94b0bbec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WalletTransactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_type', sa.Enum('customer', 'vendor', 'rider', name='wallet_user_type'), nullable=False),
    sa.Column('transaction_type', sa.Enum('top_up', 'withdrawal', 'order_payment', 'commission_deduction', 'refund', name='wallet_transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='wallet_transaction_status'), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_trans_mpesa_receipt', 'WalletTransactions', ['mpesa_receipt_number'], unique=False)
    op.create_index('idx_wallet_trans_status', 'WalletTransactions', ['status'], unique=False)
    op.create_index('idx_wallet_trans_user_type_id', 'WalletTransactions', ['user_type', 'user_id'], unique=False)
    op.create_index(op.f('ix_WalletTransactions_id'), 'WalletTransactions', ['id'], unique=True)
    op.create_index(op.f('ix_WalletTransactions_mpesa_receipt_number'), 'WalletTransactions', ['mpesa_receipt_number'], unique=False)
    op.create_index(op.f('ix_WalletTransactions_reference_id'), 'WalletTransactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_WalletTransactions_user_id'), 'WalletTransactions', ['user_id'], unique=False)
    op.drop_index(op.f('idx_vendor_remittance_deliverer_created'), table_name='vendor_remittances')
    op.drop_index(op.f('idx_vendor_remittance_vendor_created'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_vendor_remittances_deliverer_id'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_vendor_remittances_id'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_vendor_remittances_vendor_id'), table_name='vendor_remittances')
    op.drop_table('vendor_remittances')
    op.add_column('Vendors', sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Vendors', 'wallet_balance')
    op.create_table('vendor_remittances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deliverer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('full_bottles_out', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_bottles_returned', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empty_bottles_collected', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cash_expected', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('cash_collected', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'SETTLED', 'DISCREPANCY', name='vendorremittancestatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deliverer_id'], ['Deliverers.id'], name=op.f('GatePasses_deliverer_id_fkey')),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendors.id'], name=op.f('GatePasses_vendor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('GatePasses_pkey'))
    )
    op.create_index(op.f('ix_vendor_remittances_vendor_id'), 'vendor_remittances', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendor_remittances_id'), 'vendor_remittances', ['id'], unique=True)
    op.create_index(op.f('ix_vendor_remittances_deliverer_id'), 'vendor_remittances', ['deliverer_id'], unique=False)
    op.create_index(op.f('idx_vendor_remittance_vendor_created'), 'vendor_remittances', ['vendor_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_vendor_remittance_deliverer_created'), 'vendor_remittances', ['deliverer_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_WalletTransactions_user_id'), table_name='WalletTransactions')
    op.drop_index(op.f('ix_WalletTransactions_reference_id'), table_name='WalletTransactions')
    op.drop_index(op.f('ix_WalletTransactions_mpesa_receipt_number'), table_name='WalletTransactions')
    op.drop_index(op.f('ix_WalletTransactions_id'), table_name='WalletTransactions')
    op.drop_index('idx_wallet_trans_user_type_id', table_name='WalletTransactions')
    op.drop_index('idx_wallet_trans_status', table_name='WalletTransactions')
    op.drop_index('idx_wallet_trans_mpesa_receipt', table_name='WalletTransactions')
    op.drop_table('WalletTransactions')
    # ### end Alembic commands ###
