"""add staff push token

Revision ID: staff_push_token_add
Revises: 1140ea6f8341
Create Date: 2026-05-27 13:28:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'staff_push_token_add'
down_revision: Union[str, Sequence[str], None] = '1140ea6f8341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vendors', sa.Column('staff_push_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Vendors', 'staff_push_token')
    # ### end Alembic commands ###
